# Generated by Django 5.1.3 on 2024-12-22 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=280)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=280)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='post.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post')),
            ],
            options={
                'ordering': ['-like_count', '-post_date'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['like_count'], name='post_post_like_co_217265_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_date'], name='post_post_post_da_df4f28_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['like_count'], name='post_commen_like_co_01cba1_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post_date'], name='post_commen_post_da_af9773_idx'),
        ),
    ]
