# Generated by Django 5.1.5 on 2025-02-11 03:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_comment_liked_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="bookmarked_users",
            field=models.ManyToManyField(
                blank=True, related_name="bookmarked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
