# Generated by Django 5.1.5 on 2025-02-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bookmark_emoji",
            field=models.CharField(default="🔖", max_length=10),
        ),
        migrations.AddField(
            model_name="profile",
            name="comment_emoji",
            field=models.CharField(default="💭", max_length=10),
        ),
        migrations.AddField(
            model_name="profile",
            name="like_emoji",
            field=models.CharField(default="❤️", max_length=10),
        ),
        migrations.AddField(
            model_name="profile",
            name="theme",
            field=models.CharField(
                choices=[("light", "ライトモード"), ("dark", "ダークモード")],
                default="light",
                max_length=5,
            ),
        ),
    ]
