# Generated by Django 5.1.3 on 2025-02-11 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_profile_bookmark_emoji_profile_comment_emoji_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="icon_picture",
        ),
    ]
