# Generated by Django 5.1.5 on 2025-02-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_remove_profile_icon_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="icon_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
