# Generated by Django 5.1.5 on 2025-02-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0005_profile_post_content_line_height_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="post_content_line_height",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="post_vertical_padding",
        ),
        migrations.AddField(
            model_name="profile",
            name="content_spacing",
            field=models.CharField(
                choices=[
                    ("compact", "コンパクト"),
                    ("normal", "普通"),
                    ("comfortable", "広め"),
                ],
                default="normal",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="post_spacing",
            field=models.CharField(
                choices=[
                    ("compact", "コンパクト"),
                    ("normal", "普通"),
                    ("comfortable", "広め"),
                ],
                default="normal",
                max_length=15,
            ),
        ),
    ]
