# Generated by Django 5.1.5 on 2025-02-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="directmessage",
            name="is_read",
        ),
    ]
